### ISSUE TITLE
Adding firmware.uf2 doesn't work

### ISSUE THREAD

**Issue by HomelessDumpster** [sbcshop/HackyPi-Software#16]
So I got this from amazon and wanted to try it out to learn a bit abt programming. But when I add the firmware.uf2 as described then the RP1-RP2 Folder just closes and I see the HACKYPI folder again and it runs the default script again

**Comment by Darktrace01** [comment]
Using the tutorial, I tried the process again and was met with the same result. If you have determined the root of the problem, please let me know.
