### ISSUE TITLE
Hackpi doesn't work 

### ISSUE THREAD

**Issue by Met-Aph1** [sbcshop/HackyPi-Software#2]
Hi, I plugged the key to my laptop before looking at the github and the key was launching a program. Now I have followed the setup steps, my key doesn't work. Can you help me ?

**Comment by Eard-Stapa** [comment]
For me using "firmware.uf2" causes this problem and returns "No module named _future_" when trying to run code in Thonny. After using the official CircuitPython "adafruit-circuitpython-raspberry_pi_pico-en_US-8.0.5.uf2" (link at the end of step 2) everything is back to normal.

**Comment by Met-Aph1** [comment]
Oh bro, THANK YOU, it works ! 
Have a good day.
