### ISSUE TITLE
ImportError after uploading firmware.u2f

### ISSUE THREAD

**Issue by junkeller** [sbcshop/HackyPi-Software#4]
The examples do not work with firmware.u2f in your repository (which contains CircuitPython version 7.1.1) .

First I've flashed firmware.u2f from your repository. Then I've copied [lib](https://github.com/sbcshop/HackyPi-Software/tree/main/lib) to the HACKYPI drive and saved [HackyPi_Mouse_control.py](https://github.com/sbcshop/HackyPi-Software/blob/main/examples/windows/HackyPi_Mouse_control.py) as code.py.

Traceback (most recent call last):
  File "<stdin>", line 13, in <module>
  File "adafruit_hid/__init__.py", line 21, in <module>
ImportError: no module named '__future__'

The CircuitPython version 8.0.5 provided in https://circuitpython.org/board/raspberry_pi_pico/ worked. Please update firmware.u2f or remove firmware.u2f and edit [README.md](https://github.com/sbcshop/HackyPi-Software#readme), thanks!

**Comment by gjashley** [comment]
I went on much the same journey myself today

**Comment by pravarag** [comment]
Were you successfully able to flash the device with circuitpython .u2f file? For me the file gets copied and if I remove the device, and connect back it just shows the "HackyPI" volume and starts executing some default script. NO sign of circuit python :/

**Comment by netadmindave** [comment]
I had this issue as well. 
Thank you @junkeller for providing the answer.
to expand on the the solution:
The provided u2f is for v7.x of circuitpython and is incompatible with the examples that are for v8.x. Libraries from v7 are compatible with v8 but v8 is not compatible with v7. 

Insert the hackypi with the boot button held until it shows up as a drive named "RPI-RP2" then use the version of u2f referenced above, [https://circuitpython.org/board/raspberry_pi_pico/](https://circuitpython.org/board/raspberry_pi_pico/). The hackypi will reboot as soon as the u2f is finished copying. you should be able to add the libraries to the lib folder on the hackypi drive.

once the default script has finished running you can edit the code.py file using Thonny to run any of the examples or your own code.
