### ISSUE TITLE
ImportError: no module named '__future__'

### ISSUE THREAD

**Issue by walkes75** [sbcshop/HackyPi-Software#7]
Hi There,

I am using portable thonny and I am receiving such error:

>>> %Run -c $EDITOR_CONTENT
Traceback (most recent call last):
  File "<stdin>", line 13, in <module>
  File "adafruit_hid/__init__.py", line 21, in <module>
ImportError: no module named '__future__'
>>> 

How to install __future__ on device?

**Comment by netadmindave** [comment]
it is a firmware version issue https://github.com/sbcshop/HackyPi-Software/issues/4#issuecomment-1576893530

**Comment by sbcshop3** [comment]
Updated firmware.uf2 file
