### ISSUE TITLE
fix Display_Images_from_SDCard

### ISSUE THREAD

**Issue by junkeller** [sbcshop/HackyPi-Software#9]
The example [display_sdcard_images.py](https://github.com/sbcshop/HackyPi-Software/blob/main/examples/Display_images/Display_Images_from_SDCard/display_sdcard_images.py) is broken.

1) Turn on backlight: insert after "backlight display.show(main)":
tft_bl  = board.GP13
led = digitalio.DigitalInOut(tft_bl)
led.direction = digitalio.Direction.OUTPUT
led.value=True

2) the images need to be copied to the sd cards root folder (and not to a folder named images). Please correct [README.md](https://github.com/sbcshop/HackyPi-Software/blob/main/examples/Display_images/Display_Images_from_SDCard/README.md)

I've tried several different SD cards which I have formatted with FAT16 or FAT32 but the image loading time is very slowly (~3 minutes). [image_display.py](https://github.com/sbcshop/HackyPi-Software/blob/main/examples/Display_images/Display_Images_FromHackyPi/image_display.py) using the internal flash memory is loading images much faster (~4-5 seconds)

**Comment by sbcshop3** [comment]
Updated both image display-related files; download updated script with minimal adjustments. Even image rotation is sped up by cutting down on undesired pixel rotation.
